# Ground truth dataset acquisition notebook

**Description**

This notebook downloads ground truth datasets from Dresden's Open Data Portal to explore and create ground truth data for Public Urban Green Spaces (PUGS) detection. It retrieves multiple datasets including parks, green spaces, and leisure areas. These datasets will be used for training and evaluating PUGS detection models in later steps.

For **Urban Atlas Land Cover/Land use 2018 or European Urban Atlas (EUA) dataset**, User need to **download it manually** from the link provided.

**Overview of datasets**

| Data source     | Geometry type     | Dataset name     | Description      |
|-----------------|-------------------|------------------|------------------|
|  Copernicus Land Monitoring Service | Polygon/Multi-polygon | [Urban Atlas Land Cover/Land use 2018](https://land.copernicus.eu/en/products/urban-atlas/urban-atlas-2018) <br> (European Urban Atlas or EUA) <br><br> (Temporal extent of dataset: 2017-2019) | Provide land cover and land use data in Functional Urban Areas (FUA) in Europe and UK. The dataset consists of 17 urban classes with the Minimum Mapping Unit (MMU) of 0.25 ha and for 10 rural classes with the MMU of 1 ha. <br><br>**Note:** this dataset is updated every 6 years. |
| Dresden Open Data Portal  <br> (Origin from Office for Urban Green Spaces and Waste Management) | Polygon/Multi-polygon | [Park- und Grünanlagen (Flächen)](https://kommisdd.dresden.de/net3/public/ogc.ashx?Service=IKX&NodeId=751&RenderHint=TargetHTML) <br> (Park and green spaces)  <br><br> (Last update: 2020) | Provide the areas of parks and green spaces within Dresden. It includes **only green spaces that are under the administration of the state capital Dresden**. The dataset includes the areas that fall into: <br> • I1 - parks <br> • F41 - Green city square (Begrünte Stadtplätze) <br> • F43 - Other green and open spaces (Sonstige Grün- und Freiflächen) <br><br> [More details of each category](https://kommisdd.dresden.de/net3/public/ogcsl.ashx?Service=IKX&Request=GetBlobData&ts=638522102964126790&StObjectDataId=31389&ikxStoreId=) |
| Dresden Open Data Portal  <br> (Origin from Office for Geodata and Cadastre) | Polygon/Multi-polygon | [Grün- und Freiflächen](https://kommisdd.dresden.de/net3/public/ogc.ashx?Service=IKX&NodeId=1638&RenderHint=TargetHTML) <br> (Green and open spaces) <br><br> (Last update: 2024) | Provide the areas of green and open spaces in Dresden. The dataset only includes the areas that fall into: <br> • F - Green and open spaces (Grün- und Freifläche) <br> • K - Cemeteries (Friedhöfe) <br> • L - Forest/Woodland (Wald / Gehölz) <br><br> [More details of each category](https://kommisdd.dresden.de/net3/public/ogcsl.ashx?Service=IKX&Request=GetBlobData&ts=638522102964126790&StObjectDataId=31389&ikxStoreId=) |
| Dresden Open Data Portal <br> (Origin from Environment Agency) | Polygon/Multi-polygon | Erholungs- und Freizeitflächen (Recreational and leisure areas) <br><br> (Last update: 2021) | Provide the areas that fall into recreational areas according to different types of land uses. The whole dataset is [Nutzungsarten (Strukturtypen) – Kartierung](https://kommisdd.dresden.de/net3/public/ogc.ashx?Service=IKX&NodeId=1059&RenderHint=TargetHTML) <br> (Types of use - structure types - Mapping), but with the capability of WFS, specific layer can be selected to download. <br><br> [More details of each category](https://kommisdd.dresden.de/net3/public/ogcsl.ashx?Service=IKX&Request=GetBlobData&ts=638522102964126790&StObjectDataId=31389&ikxStoreId=) |
| Dresden Open Data Portal <br> (Origin from Environment Agency) | Point | [Parkanlagen, Gärten](https://kommisdd.dresden.de/net3/public/ogc.ashx?Service=IKX&NodeId=138&RenderHint=TargetHTML) (Parks, gardens) <br><br> (Last update: 2021) | Provide the location of all parks and park-like gardens within the urban area of Dresden. This dataset contains not only parks that are under the administration of the state capital Dresden but also parks under other organizations. <br><br> [More details](https://www.dresden.de/de/stadtraum/umwelt/gruenes-dresden/gruenanlagen-parks.php) |


**Input file(s)**

There is no required input files.

**Output file(s)**

4 files
- Green and Open Spaces dataset (`green_and_openspaces_dataset.geojson`)
- Park and green spaces (`parks_and_greenspaces_dataset.geojson`)
- Recreational and leisure areas (`leisure_area_dataset.geojson`)
- Parks, gardens dataset (`point_parks_and_gardens_dataset.geojson`)

**Requirements/Dependencies**

This notebook doesn't have dependency with other notebooks.

# 1. Import libraries

In [1]:
import os
import sys

# Add the root directory to Python path so that we can import the modules
root_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(root_dir)

In [2]:
import geopandas as gpd
from pugs_detection.utils import print_basic_info
from pugs_detection.ground_truth import download_ground_truth_data

# 2. Download Urban Atlas Land Cover/Land use 2018

User need to manually download this dataset from https://land.copernicus.eu/en/products/urban-atlas/urban-atlas-2018#download .
Next, user can select **Download pre-packaged data collections** and search **Dresden** to download the data.

**Requirement:** User need to have an EU Login account.

# 3. Download Green and Open Spaces

In [5]:
url = "https://kommisdd.dresden.de/net4/public/ogcapi/collections/L1266/items"
green_and_os_gdf = download_ground_truth_data(url=url, og_crs=4326, new_crs=32633)

Dataset CRS: EPSG:32633

In [6]:
geojson_output_path = "../data/raw/ground truth/green_and_openspaces_dataset.geojson"
green_and_os_gdf.to_file(geojson_output_path, driver="GeoJSON")

In [7]:
green_and_os_gdf = gpd.read_file(geojson_output_path)

In [8]:
print_basic_info(green_and_os_gdf)

Number of rows: 3024
Number of columns: 13

,blocknr,obj_id,kattime_brutto,sst_liste,sst_lv_2_liste,sst_lv_3_liste,deskn1_liste,desk2,desk3,deskn1,flaeche,aend,geometry
0,852300,21098a,919611,L Wald / Gehölz,L1 Wald nach sächs. Waldgesetz,L11 Wald nach sächs. Waldgesetz,unversiegelt (naturnahe Flächen mit VSG-Grad k...,L1,L11,0.0,15786.025474,02.05.2024 00:00:00,"POLYGON ((407724.344 5652810.146, 407715.219 5..."
1,853120,2079a,886188,F Grün- und Freiflächen,F2 Sonstige Gärten,F21 Klein- und Wochenendgärten,VSG-Grad 10 - 20 %,F2,F21,1.0,70079.538136,10.12.2018 00:00:00,"POLYGON ((408031.504 5652172.101, 408032.157 5..."
2,853320,2603a,885095,F Grün- und Freiflächen,F4 Sonstige Grünflächen im urbanen Raum,F41 Begrünte Stadtplätze,VSG-Grad 21 - 40 %,F4,F41,2.0,5079.848742,10.12.2018 00:00:00,"POLYGON ((408056.92 5651983.93, 408085.09 5651..."

# 4. Download Parks and greenspaces dataset

In [9]:
url = "https://kommisdd.dresden.de/net4/public/ogcapi/collections/L569/items"
park_and_gs_gdf = download_ground_truth_data(url=url, og_crs=4326, new_crs=32633)

Dataset CRS: EPSG:32633

In [10]:
geojson_output_path = "../data/raw/ground truth/parks_and_greenspaces_dataset.geojson"
park_and_gs_gdf.to_file(geojson_output_path, driver="GeoJSON")

In [11]:
park_and_gs_gdf = gpd.read_file(geojson_output_path)

In [12]:
print_basic_info(park_and_gs_gdf)

Number of rows: 587
Number of columns: 8

,id,oa,ort,groesse,anlage,antrag,bezirk,geometry
0,6067/03,O Schönfeld-Weißig,Straße des Friedens (Pappritz) - zw. Am Dorfte...,348.18,Park- und Grünanlagen,http://www.dresden.de/media/pdf/formulare/Antr...,34,"MULTIPOLYGON (((419624.766 5654422.363, 419621..."
1,0010/04,StB Altstadt,Bürgerwiese - zw. Lennéstraße u. Zoologischen ...,36540.13,Park- und Grünanlagen,http://www.dresden.de/media/pdf/formulare/Antr...,20,"POLYGON ((412242.5 5654910.433, 412238.775 565..."
2,5763/01,StB Prohlis,Reicker Straße - zw. Hans-Jüchser-Straße u. Be...,1105.00,Park- und Grünanlagen,http://www.dresden.de/media/pdf/formulare/Antr...,27,"POLYGON ((414516.005 5652671.438, 414515.96 56..."

# 5. Download Parks (I type) dataset

In [13]:
# WFS service URL
url = "https://kommisdd.dresden.de/net3/public/ogcsl.ashx"

# WFS parameters - removed outputFormat parameter since XML is the only option
params = {
    "NODEID": "1059",
    "Service": "WFS",
    "typenames": "cls:L1263",
    "request": "GetFeature",
    "version": "2.0.0",  # Using standard WFS 2.0.0
}

leisure_gdf = download_ground_truth_data(
    url=url, params=params, og_crs=25833, new_crs=32633
)

Dataset CRS: EPSG:32633

In [14]:
geojson_output_path = "../data/raw/ground truth/leisure_area_dataset.geojson"
leisure_gdf.to_file(geojson_output_path, driver="GeoJSON")

In [15]:
leisure_gdf = gpd.read_file(geojson_output_path)

In [16]:
print_basic_info(leisure_gdf)

Number of rows: 498
Number of columns: 15

,gml_id,blocknr,obj_id,kattime_brutto,kattime,sst_liste,sst_lv_2_liste,sst_lv_3_liste,deskn1_liste,desk2,desk3,deskn1,flaeche,aend,geometry
0,L1263.917771,853370,2011a,886840,917771,E Sport- und Freizeitanlagen,E3 Sonstige Sport- und Freizeitanlagen,"E32 Sonstige Sport- und Freizeitanlagen, bebaut",VSG-Grad 81 - 100 %,E3,E32,5,2970.683268,2018-12-10,"POLYGON ((408186.782 5651865.549, 408186.794 5..."
1,L1263.917840,249060,8215a,891720,917840,E Sport- und Freizeitanlagen,E3 Sonstige Sport- und Freizeitanlagen,"E31 Sonstige Sport- und Freizeitanlagen, unb...",VSG-Grad 41 - 60 %,E3,E31,3,5764.964623,2018-12-10,"POLYGON ((408445.187 5661903.813, 408443.882 5..."
2,L1263.919778,945120,21088a,895546,919778,"I Parkanlagen, Zoo, Botanischer Garten",I1 Parks,I11 Parks,VSG-Grad 10 - 20 %,I1,I11,1,6047.863237,2024-04-24,"POLYGON ((408818.015 5653833.579, 408807.323 5..."

# 6. Download Parks point dataset

In [17]:
url = "https://kommisdd.dresden.de/net4/public/ogcapi/collections/L104/items"
park_point_gdf = download_ground_truth_data(url=url, og_crs=4326, new_crs=32633)

Dataset CRS: EPSG:32633

In [18]:
geojson_output_path = "../data/raw/ground truth/point_parks_and_gardens_dataset.geojson"
park_point_gdf.to_file(geojson_output_path, driver="GeoJSON")

In [19]:
park_point_gdf = gpd.read_file(geojson_output_path)

In [20]:
print_basic_info(park_point_gdf)

Number of rows: 64
Number of columns: 6

,einrichtung,lage,einrichtungsart,url,ds_modified,geometry
0,Räcknitzer Park,Räcknitzhöhe,Park,de.wikipedia.org/wiki/Volkspark_R%C3%A4cknitz,13.03.2025 13:42:04,POINT (411557.217 5653379.243)
1,Palaisgarten,Palaisplatz,Park,www.stadtwikidd.de/wiki/Palaisgarten,14.03.2025 13:23:16,POINT (411462.772 5657203.894)
2,Park Schloß Eckberg,Bautzner Straße 134,Park,www.schloss-eckberg.de/der-schlosspark/,14.03.2025 13:33:16,POINT (416057.391 5657751.021)