# Import library

In [1]:
import os
import sys

# Add the root directory to Python path so that we can import the modules
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(root_dir)

In [2]:
import geopandas as gpd
import pandas as pd
import rasterio
import matplotlib.colors as mcolors
import pugs_detection.utils as utils

# Import data

## Green space from landuse key

In [3]:
file_path = '../data/raw/osm/green space/green_landuse_area_dresden.geojson'
green_landuse_area = utils.load_osm_data(file_path, 32633)

In [4]:
utils.print_basic_info(green_landuse_area)

Number of rows: 12620
Number of columns: 126

,element,id,landuse,name,denomination,religion,wikidata,check_date:opening_hours,opening_hours,website,...,substance,utility,was:man_made,name:en,level,material,type,name:hsb,source:outline,geometry
0,node,593500300,meadow,Fasanenwiese,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,None,POINT (409534.707 5668038.509)
1,node,593504848,forest,Fuchsbruch,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,None,POINT (409318.056 5667413.545)
2,relation,6128,forest,Dresdner Heide,None,None,Q8905,NaT,None,None,...,None,None,None,None,None,None,multipolygon,Drježdźanska hola,None,"MULTIPOLYGON (((422682.225 5662327.517, 422778..."
3,relation,22720,forest,Tharandter Wald,None,None,Q2409158,NaT,None,None,...,None,None,None,None,None,None,multipolygon,Tharandtski lěs,None,"MULTIPOLYGON (((391086.484 5644235.349, 391133..."
4,relation,51861,meadow,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,multipolygon,None,None,"POLYGON ((422507.812 5648579.133, 422497.737 5..."

In [5]:
# Select only some columns
green_landuse_area = green_landuse_area[['element', 'id', 'landuse', 
                                         'name', 'barrier', 'note', 
                                         'opening_hours', 'access', 'description', 
                                         'leisure', 'tourism', 'surface', 
                                         'landcover', 'amenity', 'natural', 
                                         'type', 'geometry']]

In [6]:
green_landuse_area['area'] = green_landuse_area['geometry'].area

## Green space from leisure key

In [7]:
file_path = '../data/raw/osm/green space/green_leisure_area_dresden.geojson'
green_leisure_area = utils.load_osm_data(file_path, 32633)

In [8]:
utils.print_basic_info(green_leisure_area)

Number of rows: 3963
Number of columns: 149

,element,id,created_by,leisure,wheelchair,access,name,opening_hours,operator,sport,...,name:de,pitch:net,pitch:net:material,pitch:net:overhang,construction,operator:short,animal_training,type,name:fr,geometry
0,node,255545201,Potlatch 0.8a,playground,no,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (409940.451 5652983.729)
1,node,262693384,JOSM,playground,limited,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (414361.811 5663180.907)
2,node,266593887,None,playground,None,yes,Würzburger Straße - Park,Mo-Su 08:00-22:00,Landeshauptstadt Dresden,None,...,None,None,None,None,None,None,None,None,None,POINT (409905.579 5653957.552)
3,node,269751929,None,playground,None,yes,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (415406.577 5664375.327)
4,node,269949803,None,playground,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (400428.614 5648263.427)

In [9]:
# Select only some columns
green_leisure_area = green_leisure_area[['element', 'id', 'access', 
                                         'leisure', 'name', 'opening_hours', 'indoor',
                                         'operator', 'description', 'playground',
                                         'note', 'surface', 'fee', 
                                         'barrier', 'landuse', 'natural',
                                         'charge', 'landcover', 'fence_type', 'garden:type',
                                         'wall', 'type', 'geometry']]

In [10]:
green_leisure_area['area'] = green_leisure_area['geometry'].area

## Green space from nature key

In [11]:
file_path = '../data/raw/osm/green space/green_natural_area_dresden.geojson'
green_natural_area = utils.load_osm_data(file_path, 32633)

In [12]:
utils.print_basic_info(green_natural_area)

Number of rows: 4610
Number of columns: 80

,element,id,natural,wetland,name,source:name,old_name,source,boundary,denotation,...,comment,area,check_date,area:highway,fee,species:wikipedia,type,nature,protected_area,geometry
0,node,2583496631,wetland,swamp,None,None,None,None,None,None,...,None,None,NaT,None,None,None,None,None,None,POINT (418793.941 5666708.208)
1,node,9042465204,wood,None,Kirsten Buschgen,Meilenblatt Sachsen 1783,None,None,None,None,...,None,None,NaT,None,None,None,None,None,None,POINT (427333.114 5654745.676)
2,node,9124027180,wood,None,Der Strang,None,Strange Holtz,Meilenblätter Sachsen 1783 Blatt 264,None,None,...,None,None,NaT,None,None,None,None,None,None,POINT (426484.877 5665108.539)
3,relation,9792,wood,None,None,None,None,None,None,None,...,None,None,NaT,None,None,None,multipolygon,None,None,"POLYGON ((408018.949 5652817.259, 408004.276 5..."
4,relation,10401,wood,None,None,None,None,None,None,None,...,None,None,NaT,None,None,None,multipolygon,None,None,"POLYGON ((419299.333 5656612.491, 419298.429 5..."

In [13]:
green_natural_area = green_natural_area[['element', 'id', 'natural', 
                                         'name', 'note', 'leisure',
                                         'description', 'barrier', 'landuse',
                                         'landcover', 'access', 'fee', 'type', 'geometry']]

In [14]:
green_natural_area['area'] = green_natural_area['geometry'].area

## Green space from camp site

In [15]:
file_path = '../data/raw/osm/green space/green_campsite_area_dresden.geojson'
green_campsite_area = utils.load_osm_data(file_path, 32633)

In [16]:
utils.print_basic_info(green_campsite_area)

Number of rows: 199
Number of columns: 115

,element,id,created_by,tourism,access,addr:city,addr:country,addr:housenumber,addr:postcode,addr:street,...,motor_vehicle,beds,group_only,guest_house,rooms,attraction,capacity:disabled,seasonal,socket:cee_blue,geometry
0,node,257564076,JOSM,picnic_site,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (411597.918 5665030.941)
1,node,257564078,JOSM,picnic_site,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (411626.748 5664796.911)
2,node,257922815,JOSM,picnic_site,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (411564.728 5665084.269)
3,node,257923367,None,picnic_site,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (411586.657 5667217.952)
4,node,258326088,None,camp_site,private,Dresden,DE,81,01277,Tolkewitzer Straße,...,None,None,None,None,None,None,None,None,None,POINT (417186.97 5654969.5)

In [17]:
green_campsite_area['area'] = green_campsite_area['geometry'].area

## POI/Amenity from amenity

In [18]:
file_path = '../data/raw/osm/amenity/poi_amenity_dresden.geojson'
poi_amenity = utils.load_osm_data(file_path, 32633)

In [19]:
utils.print_basic_info(poi_amenity)

Number of rows: 10248
Number of columns: 83

,element,id,amenity,backrest,description,direction,material,seats,wikimedia_commons,created_by,...,deposit_ring,support,seats:separated,outdoor_seating,leisure,barrier,height,area,man_made,geometry
0,node,251567329,bench,yes,Bank am Zickzack-Weg,100,wood,3,File:Bank am Zickzackweg.jpg,None,...,None,None,None,None,None,None,None,None,None,POINT (403728.926 5649371.357)
1,node,255298026,bench,yes,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (415787.203 5655716.144)
2,node,255925960,waste_basket,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (409010.616 5654975)
3,node,257567101,bench,None,None,None,None,None,None,JOSM,...,None,None,None,None,None,None,None,None,None,POINT (411676.54 5669898.692)
4,node,257934358,bench,yes,None,None,None,None,None,JOSM,...,None,None,None,None,None,None,None,None,None,POINT (410258.291 5668038.07)

## POI/Amenity from leisure

In [20]:
file_path = '../data/raw/osm/amenity/poi_leisure_dresden.geojson'
poi_leisure = utils.load_osm_data(file_path, 32633)

In [21]:
utils.print_basic_info(poi_leisure)

Number of rows: 1611
Number of columns: 84

,element,id,created_by,leisure,wheelchair,access,name,opening_hours,operator,sport,...,playground:springy,fixme,start_date,contact:email,contact:mobile,contact:website,addr:suburb,construction,type,geometry
0,node,255545201,Potlatch 0.8a,playground,no,None,None,None,None,None,...,None,None,NaT,None,None,None,None,None,None,POINT (409940.451 5652983.729)
1,node,262693384,JOSM,playground,limited,None,None,None,None,None,...,None,None,NaT,None,None,None,None,None,None,POINT (414361.811 5663180.907)
2,node,266593887,None,playground,None,yes,Würzburger Straße - Park,Mo-Su 08:00-22:00,Landeshauptstadt Dresden,None,...,None,None,NaT,None,None,None,None,None,None,POINT (409905.579 5653957.552)
3,node,269751929,None,playground,None,yes,None,None,None,None,...,None,None,NaT,None,None,None,None,None,None,POINT (415406.577 5664375.327)
4,node,269949803,None,playground,None,None,None,None,None,None,...,None,None,NaT,None,None,None,None,None,None,POINT (400428.614 5648263.427)

## POI/Amenity from tourism

In [22]:
file_path = '../data/raw/osm/amenity/poi_viewpoint_dresden.geojson'
poi_viewpoint = utils.load_osm_data(file_path, 32633)

In [23]:
utils.print_basic_info(poi_viewpoint)

Number of rows: 216
Number of columns: 75

,element,id,highway,toilets:wheelchair,tourism,wheelchair,name,name:de,noexit,description,...,source,tower:construction,charge,comment,old_name,loc_name,subject:wikipedia,building:levels,name:en,geometry
0,node,67366424,turning_circle,yes,viewpoint,yes,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (403904.735 5663529.148)
1,node,71744963,None,None,viewpoint,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (406659.489 5667933.973)
2,node,248567811,None,None,viewpoint,no,Am Zwingergraben,Am Zwingergraben,yes,None,...,None,None,None,None,None,None,None,None,None,POINT (411130.285 5656571.446)
3,node,248966496,None,None,viewpoint,limited,Turm Kreuzkirche,Turm Kreuzkirche,None,Aufstieg über Eingang F der Kreuzkirche,...,None,None,None,None,None,None,None,None,None,POINT (411603.505 5656002.758)
4,node,251043383,None,None,viewpoint,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,POINT (409649.619 5653164.474)

# Walking path

In [24]:
file_path = '../data/raw/osm/network/footpath_network_edges.geojson'
footpath_network_edges = utils.load_osm_data(file_path, 32633)

Skipping field highway: unsupported OGR type: 5
Skipping field maxspeed: unsupported OGR type: 5
Skipping field name: unsupported OGR type: 5
Skipping field service: unsupported OGR type: 5
Skipping field lanes: unsupported OGR type: 5
Skipping field bridge: unsupported OGR type: 5
Skipping field width: unsupported OGR type: 5
Skipping field ref: unsupported OGR type: 5
Skipping field tunnel: unsupported OGR type: 5

In [25]:
utils.print_basic_info(footpath_network_edges)

Number of rows: 313296
Number of columns: 12

,u,v,key,osmid,oneway,reversed,length,access,junction,est_width,area,geometry
0,442734,1839778041,0,1338016415,False,True,72.940783,None,None,None,None,"LINESTRING (411407.486 5652433.485, 411472.711..."
1,442734,442736,0,92,False,False,169.821618,None,None,None,None,"LINESTRING (411407.486 5652433.485, 411445.258..."
2,442734,9907191675,0,105,False,False,55.779311,None,None,None,None,"LINESTRING (411407.486 5652433.485, 411369.586..."
3,442736,442738,0,92,False,False,85.329804,None,None,None,None,"LINESTRING (411576.808 5652437.616, 411597.21 ..."
4,442736,442734,0,92,False,True,169.821618,None,None,None,None,"LINESTRING (411576.808 5652437.616, 411518.084..."

## Filter only footpath that access is public

In [26]:
footpath_network_edges = footpath_network_edges[(footpath_network_edges['access']=='permissive')|
                                                (footpath_network_edges['access']=='yes')|
                                                (footpath_network_edges['access']=='public')|
                                                (footpath_network_edges['access']=='foot')]

# Define custom color map for visualization

In [27]:
# Create custom color map
colors = mcolors.ListedColormap(['#ff4d4d', '#4dff4d'])  # Red for private, Green for public

# Process data

In [28]:
all_lulc_space_gdf = pd.concat([green_landuse_area, green_leisure_area, green_natural_area, green_campsite_area], ignore_index=True)

In [29]:
all_lulc_space_gdf = all_lulc_space_gdf[['element', 'id', 'landuse', 'name', 'barrier', 'note', 'opening_hours',
       'access', 'description', 'leisure', 'tourism', 'surface', 'landcover', 'indoor',
       'natural', 'type', 'geometry', 'area', 'operator',
       'playground', 'fee', 'charge', 'fence_type', 'garden:type']]

In [30]:
utils.print_basic_info(all_lulc_space_gdf)

Number of rows: 21392
Number of columns: 24

,element,id,landuse,name,barrier,note,opening_hours,access,description,leisure,...,natural,type,geometry,area,operator,playground,fee,charge,fence_type,garden:type
0,node,593500300,meadow,Fasanenwiese,None,None,None,None,None,None,...,None,None,POINT (409534.707 5668038.509),0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN
1,node,593504848,forest,Fuchsbruch,None,None,None,None,None,None,...,None,None,POINT (409318.056 5667413.545),0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN
2,relation,6128,forest,Dresdner Heide,None,None,None,None,None,None,...,None,multipolygon,"MULTIPOLYGON (((422682.225 5662327.517, 422778...",5.293124e+07,NaN,NaN,NaN,NaN,NaN,NaN
3,relation,22720,forest,Tharandter Wald,None,None,None,None,None,None,...,None,multipolygon,"MULTIPOLYGON (((391086.484 5644235.349, 391133...",5.613852e+07,NaN,NaN,NaN,NaN,NaN,NaN
4,relation,51861,meadow,None,None,None,None,None,None,None,...,None,multipolygon,"POLYGON ((422507.812 5648579.133, 422497.737 5...",3.736947e+04,NaN,NaN,NaN,NaN,NaN,NaN

## Spatial join

**Note:** This step won't remove the polygon that is inside the bigger polygon. Small polygon's attributes will also be concatenated with Bigger polygon.

In [31]:
joined_lulc_space = all_lulc_space_gdf.sjoin(all_lulc_space_gdf, how='left', predicate='contains')

In [32]:
utils.print_basic_info(joined_lulc_space)

Number of rows: 23497
Number of columns: 48

,element_left,id_left,landuse_left,name_left,barrier_left,note_left,opening_hours_left,access_left,description_left,leisure_left,...,indoor_right,natural_right,type_right,area_right,operator_right,playground_right,fee_right,charge_right,fence_type_right,garden:type_right
0,node,593500300,meadow,Fasanenwiese,None,None,None,None,None,None,...,NaN,None,None,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
1,node,593504848,forest,Fuchsbruch,None,None,None,None,None,None,...,NaN,None,None,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,relation,6128,forest,Dresdner Heide,None,None,None,None,None,None,...,NaN,None,None,26701.181844,NaN,NaN,NaN,NaN,NaN,NaN
2,relation,6128,forest,Dresdner Heide,None,None,None,None,None,None,...,NaN,None,NaN,26701.181844,"Landeshauptstadt Dresden, Amt f. Stadtgrün u. ...",NaN,None,None,None,NaN
2,relation,6128,forest,Dresdner Heide,None,None,None,None,None,None,...,None,None,None,7390.726879,None,None,None,None,None,None

**Note:** Some green spaces also contain the small area that has non-green/non-vegetation surface. But then again, if the area of small polygon is less than 100 sq.m., it is filtered out in te later step.

# Classify green spaces to be public/non-public

## 1. Use fee and charge tag to classify private area

In [33]:
joined_lulc_space.loc[(joined_lulc_space['fee_left'] == 'yes')|
                      (~joined_lulc_space['charge_left'].isna()), 'is_public'] = 'no'

## 2. Use access tag to classify
- Access = yes/permissive -> public
- Access = no/private/customers/restricted -> private

In [34]:
joined_lulc_space.loc[((joined_lulc_space['access_left'] == 'yes')|
                       (joined_lulc_space['access_left'] == 'permissive'))& 
                       (joined_lulc_space['is_public'].isna()), 'is_public'] = 'yes'

In [35]:
joined_lulc_space.loc[(joined_lulc_space['access_left']!='yes')&
                      (joined_lulc_space['access_left']!='permissive')&
                      (~joined_lulc_space['access_left'].isna())&
                      (joined_lulc_space['is_public'].isna()), 'is_public'] = 'no'

## 3. Use tag to classify non-public area
- tourism=zoo
- leisure=golf_course
- garden:type=residential/private
- landuse=vineyard

In [36]:
joined_lulc_space['garden:type_left'].unique()

array([nan, None, 'botanical', 'community', 'residential', 'show_garden',
       'flowerbed', 'private', 'landscaping'], dtype=object)

In [37]:
joined_lulc_space.loc[((joined_lulc_space['tourism_left']=='zoo')|
                       (joined_lulc_space['leisure_left']=='golf_course')|
                       (joined_lulc_space['garden:type_left']=='residential')|
                       (joined_lulc_space['garden:type_left']=='private')|
                       (joined_lulc_space['landuse_left']=='vineyard'))&
                       (joined_lulc_space['is_public'].isna()), 'is_public'] = 'no'

## 4. Use leisure=park tag to classify public area

In [38]:
joined_lulc_space.loc[(joined_lulc_space['leisure_left']=='park')&
                      (joined_lulc_space['is_public'].isna()), 'is_public'] = 'yes'

## 5. Use another leisure and landuse tag to classify public/non-public

If leisure=nature_reserve or landuse=cemetery, classify as public

In [39]:
joined_lulc_space.loc[((joined_lulc_space['leisure_left']=='nature_reserve')|
                       (joined_lulc_space['landuse_left']=='cemetery'))&
                       (joined_lulc_space['is_public'].isna()), 'is_public'] = 'yes'

If landuse=allotments, classify as non-public

In [40]:
joined_lulc_space.loc[(joined_lulc_space['landuse_left']=='allotments')&
                      (joined_lulc_space['is_public'].isna()), 'is_public'] = 'no'

## 6. Use barrier tag to classify non-public area

In [41]:
joined_lulc_space.loc[(~joined_lulc_space['barrier_left'].isna())&
                      (joined_lulc_space['is_public'].isna()), 'is_public'] = 'no'

In [42]:
# Doesn't want to make false report on the percentage of the green space (area)
show_pc = joined_lulc_space.drop_duplicates(subset=['id_left'])

In [43]:
utils.print_classification_report(show_pc)

total LULC spaces: 21326
total labeled LULC spaces: 3478
total public LULC spaces: 1369
total non-public LULC spaces: 2109
--------------------
total LULC spaces (area): 384202593.27397215
percentage of labeled LULC spaces (area): 10.876391421833729
percentage of public LULC spaces (area): 5.583938768636684
percentage of non-public LULC spaces (area): 5.292452653197045

# Create additional information to classify public/non-public area

Presence/number of benches, playgrounds, waste baskets, picnic tables, and viewpoints for each area

In [44]:
joined_lulc_space_with_poi = (joined_lulc_space
                              .pipe(utils.calculate_poi_number, poi_amenity, 'amenity')
                              .pipe(utils.calculate_poi_number, poi_leisure, 'leisure')
                              .pipe(utils.calculate_poi_number, poi_viewpoint, 'tourism')
                              .pipe(utils.calculate_footpath_length, footpath_network_edges))

In [45]:
joined_lulc_space_with_poi.head()

,element_left,id_left,landuse_left,name_left,barrier_left,note_left,opening_hours_left,access_left,description_left,leisure_left,...,charge_right,fence_type_right,garden:type_right,is_public,bench,waste_basket,picnic_table,playground,viewpoint,length
0,node,593500300,meadow,Fasanenwiese,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000000
1,node,593504848,forest,Fuchsbruch,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.000000
2,relation,6128,forest,Dresdner Heide,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,140.0,3.0,12.0,6.0,3.0,4864.166807
3,relation,6128,forest,Dresdner Heide,None,None,None,None,None,None,...,None,None,NaN,NaN,140.0,3.0,12.0,6.0,3.0,4864.166807
4,relation,6128,forest,Dresdner Heide,None,None,None,None,None,None,...,None,None,None,NaN,140.0,3.0,12.0,6.0,3.0,4864.166807

# Classify green spaces based on additional indicators

Refer to mapping guide of European Urban Atlas

## If the area is forest and there is trace of recreational activity, classify the area as public

In [46]:
joined_lulc_space_with_poi.loc[((joined_lulc_space_with_poi['bench']>0)|
                                (joined_lulc_space_with_poi['waste_basket']>0)|
                                (joined_lulc_space_with_poi['playground']>0)|
                                (joined_lulc_space_with_poi['picnic_table']>0)|
                                (joined_lulc_space_with_poi['length']>0))&
                                (joined_lulc_space_with_poi['landuse_left']=='forest')&
                                (joined_lulc_space_with_poi['is_public'].isna()), 'is_public'] = 'yes'

In [47]:
# Doesn't want to make false report on the percentage of the green space (area)
show_pc = joined_lulc_space_with_poi.drop_duplicates(subset=['id_left'])

In [48]:
utils.print_classification_report(show_pc)

total LULC spaces: 21326
total labeled LULC spaces: 3651
total public LULC spaces: 1542
total non-public LULC spaces: 2109
--------------------
total LULC spaces (area): 384202593.27397215
percentage of labeled LULC spaces (area): 63.94059740126843
percentage of public LULC spaces (area): 58.648144748071374
percentage of non-public LULC spaces (area): 5.292452653197045

## If there is the viewpoint in area, classify as public

In [49]:
joined_lulc_space_with_poi.loc[(joined_lulc_space_with_poi['viewpoint']>0)&
                               (joined_lulc_space_with_poi['is_public'].isna()), 'is_public'] = 'yes'

In [50]:
# Doesn't want to make false report on the percentage of the green space (area)
show_pc = joined_lulc_space_with_poi.drop_duplicates(subset=['id_left'])

In [51]:
utils.print_classification_report(show_pc)

total LULC spaces: 21326
total labeled LULC spaces: 3711
total public LULC spaces: 1602
total non-public LULC spaces: 2109
--------------------
total LULC spaces (area): 384202593.27397215
percentage of labeled LULC spaces (area): 65.03169333317541
percentage of public LULC spaces (area): 59.73924067997838
percentage of non-public LULC spaces (area): 5.292452653197045

# Classified public/non-public area by using small polygon inside larger polygon

In [52]:
unlabeled_lulc_space = joined_lulc_space_with_poi[joined_lulc_space_with_poi['is_public'].isna()]

To classify the accessibility of green spaces (larger polygon), I use the area of small polygon inside them to classify.
- If total public area inside polygon are more than non-public, that polygon is classifies as public
- If total non-public area + unclassified area inside polygon are more than public, that polygon is classifies as non-public

**Note:** Some polygon might also contain the node (playground, pitch, garden, etc.). I also assign the area for the node to make it be able to aggregate with small polygon's area. So, below code is or finding the average percentage of playground, pitch, garden, etc. in the green space based on the classified green spaces data.

In [53]:
leisure_node_element_list = joined_lulc_space_with_poi[(joined_lulc_space_with_poi['element_right']=='node')&
                                                       (joined_lulc_space_with_poi['id_left']!=joined_lulc_space_with_poi['id_right'])]['leisure_right'].unique().tolist()
landuse_node_element_list = joined_lulc_space_with_poi[(joined_lulc_space_with_poi['element_right']=='node')&
                                                       (joined_lulc_space_with_poi['id_left']!=joined_lulc_space_with_poi['id_right'])]['landuse_right'].unique().tolist()
print("leisure tag of node element in polygon:", leisure_node_element_list)
print("landuse tag of node element in polygon:", landuse_node_element_list)

leisure tag of node element in polygon: [None, 'pitch', 'playground', 'picnic_table', 'garden']
landuse tag of node element in polygon: [None, 'meadow', 'forest']

The rules to classify polygon:
- Public >= 50% -> public
- Non-public+unclassified >= 50% -> non-public

In [54]:
final_classified_lulc_space = utils.classification_with_smaller_area(joined_lulc_space_with_poi)

leisure tag of node element in polygon: [None, 'pitch', 'playground', 'picnic_table', 'garden']
landuse tag of node element in polygon: [None, 'meadow', 'forest']
estimated average percentage of each leisure/landuse: {'forest': 7, 'playground': 6, 'pitch': 6, 'meadow': 6, 'garden': 2}
final estimated average percentage area: {'forest': 7, 'playground': 6, 'pitch': 6, 'meadow': 6, 'garden': 2, None: 1, 'picnic_table': 1}
larger polygon id: 18622415    small polygon id: [1354952533]
larger polygon id: 165505041    small polygon id: [163418178]
larger polygon id: 190265844    small polygon id: [1221271894, 1221288896, 1221293174, 1221291997, 1221291509, 1221271555]
larger polygon id: 190708040    small polygon id: [190708057]
larger polygon id: 238260545    small polygon id: [2463155102, 3518017063, 1097604854, 345110108, 345110103]
larger polygon id: 268604310    small polygon id: [926115769]
larger polygon id: 268604316    small polygon id: [926115770]
larger polygon id: 329102185    small polygon id: [307673236, 1219826678, 3724867245, 329102191, 28079891]
larger polygon id: 366304801    small polygon id: [1187379215, 11026131972, 1251158963]
larger polygon id: 760827594    small polygon id: [878633712, 760827595]
larger polygon id: 1082413197    small polygon id: [14401858, 1082413198]
larger polygon id: 1354952533    small polygon id: [18622415]
larger polygon id: 39362138    small polygon id: [413292359, 413292374]
larger polygon id: 232803037    small polygon id: [1112266904]
larger polygon id: 4779059    small polygon id: [359275692]
larger polygon id: 163418178    small polygon id: [165505041]

In [55]:
# doesn't want to make false report on the percentage of the green space (area)
show_pc = final_classified_lulc_space.drop_duplicates(subset=['id_left'])

In [56]:
utils.print_classification_report(show_pc)

total LULC spaces: 21326
total labeled LULC spaces: 3727
total public LULC spaces: 1602
total non-public LULC spaces: 2125
--------------------
total LULC spaces (area): 384202593.27397215
percentage of labeled LULC spaces (area): 65.12823949202729
percentage of public LULC spaces (area): 59.73924067997838
percentage of non-public LULC spaces (area): 5.3889988120489205

# Clean data

## Filter area that is < 100 m2 out

In [57]:
filtered_lulc_space = final_classified_lulc_space[final_classified_lulc_space['area_left'] > 100]

In [58]:
show_pc = filtered_lulc_space.drop_duplicates(subset=['id_left'])

In [59]:
utils.print_classification_report(show_pc)

total LULC spaces: 17566
total labeled LULC spaces: 3076
total public LULC spaces: 1271
total non-public LULC spaces: 1805
--------------------
total LULC spaces (area): 384076243.8356094
percentage of labeled LULC spaces (area): 65.14621073985225
percentage of public LULC spaces (area): 59.75720871771182
percentage of non-public LULC spaces (area): 5.389002022140452

## Remove indoor space out

In [60]:
print("indoor tag:", filtered_lulc_space['indoor_left'].unique())
print("indoor tag (polygon/node inside bigger pollygon):", filtered_lulc_space['indoor_right'].unique())

indoor tag: [nan None]
indoor tag (polygon/node inside bigger pollygon): [nan None 'yes' 'no']

In [61]:
filtered_lulc_space = filtered_lulc_space[filtered_lulc_space['indoor_left']!='yes']

In [62]:
utils.print_classification_report(show_pc)

total LULC spaces: 17566
total labeled LULC spaces: 3076
total public LULC spaces: 1271
total non-public LULC spaces: 1805
--------------------
total LULC spaces (area): 384076243.8356094
percentage of labeled LULC spaces (area): 65.14621073985225
percentage of public LULC spaces (area): 59.75720871771182
percentage of non-public LULC spaces (area): 5.389002022140452

## Remove polygon that is not green space/surface isn't grass out (if surface value is specified) and keep it in another df

Note: Only non-green space inside the green space polygon are kept

In [63]:
small_polygon_id = filtered_lulc_space[filtered_lulc_space['id_left']!=filtered_lulc_space['id_right']]['id_right'].unique().tolist()
all_polygon_id = filtered_lulc_space['id_left'].unique()

In [64]:
print("surface:", filtered_lulc_space['surface_left'].unique(), "\n")
print("leisure:", filtered_lulc_space['leisure_left'].unique(), "\n")
print("natural:", filtered_lulc_space['natural_left'].unique())

surface: [None 'grass' 'gravel' 'tartan' 'artificial_turf' 'clay' 'sand' 'asphalt'
 'ground' 'fine_gravel' 'compacted' 'dirt' 'rubber' 'concrete'
 'paving_stones' 'sett' 'unpaved' 'pebblestone' 'wood' 'woodchips'
 'decoturf' 'textile' 'dirt/sand' 'acrylic' 'paved' 'textile_chips' nan]

leisure: [None 'park' 'water_park' 'playground' 'garden' 'pitch' 'nature_reserve'
 'golf_course' 'dog_park']

natural: [None 'scrub' 'grassland' 'wetland' 'wood' 'water' 'plant' 'heath']

In [65]:
non_green_surface = filtered_lulc_space[(filtered_lulc_space['id_left'].isin(small_polygon_id))&
                                        (((filtered_lulc_space['surface_left']!='grass')&
                                          (~filtered_lulc_space['surface_left'].isna()))|
                                          (filtered_lulc_space['leisure_left']=='water_park')|
                                          (filtered_lulc_space['natural_left']=='water'))]

In [66]:
non_green_surface = non_green_surface.drop_duplicates(subset=['id_left'])

In [67]:
print("total non-green areas:", non_green_surface.shape[0])

total non-green areas: 115

In [68]:
print("average area of small polygon that is non-green surface:", non_green_surface['area_left'].mean())

average area of small polygon that is non-green surface: 712.5293632699319

In [69]:
final_green_spaces = filtered_lulc_space[~(((filtered_lulc_space['surface_left']!='grass')&
                                            (~filtered_lulc_space['surface_left'].isna()))|
                                            (filtered_lulc_space['leisure_left']=='water_park')|
                                            (filtered_lulc_space['natural_left']=='water'))]

In [70]:
# Doesn't want to make false report on the percentage of the green space (area)
show_pc = final_green_spaces.drop_duplicates(subset=['id_left'])

In [71]:
utils.print_classification_report(show_pc)

total LULC spaces: 17076
total labeled LULC spaces: 2966
total public LULC spaces: 1236
total non-public LULC spaces: 1730
--------------------
total LULC spaces (area): 383391986.66596055
percentage of labeled LULC spaces (area): 65.22513844862182
percentage of public LULC spaces (area): 59.859880781212404
percentage of non-public LULC spaces (area): 5.365257667409407

# Overlay

1. Overlay between green spaces and non-green spaces
2. Overlay between public and non-public green spaces

## Overlay between green spaces and non-green spaces

In [72]:
final_green_spaces = final_green_spaces.drop_duplicates(subset=['id_left'])

In [73]:
final_green_spaces = gpd.overlay(final_green_spaces, non_green_surface, how='difference')

In [74]:
utils.print_classification_report(final_green_spaces)

total LULC spaces: 17076
total labeled LULC spaces: 2966
total public LULC spaces: 1236
total non-public LULC spaces: 1730
--------------------
total LULC spaces (area): 383391986.66596055
percentage of labeled LULC spaces (area): 65.22513844862182
percentage of public LULC spaces (area): 59.859880781212404
percentage of non-public LULC spaces (area): 5.365257667409407

In [75]:
print("average area of unclassified green spaces:", final_green_spaces[final_green_spaces['is_public'].isna()]['area_left'].mean())

average area of unclassified green spaces: 9448.903796042954

## Overlay between public and non-public green spaces

In [76]:
public_green_space = final_green_spaces[final_green_spaces['is_public'] == 'yes']
non_public_green_space = final_green_spaces[final_green_spaces['is_public'] == 'no']

In [77]:
pugs_within_nonpugs_list = public_green_space.sjoin(non_public_green_space, how='inner', predicate='within', rsuffix='_right_2')['id_left_left'].unique().tolist()

In [78]:
# After taking the difference (the area that mark as pugs inside non-pugs will be gone)
# This can be argue -> to ensure the minimum public green space
public_green_space[public_green_space['id_left'].isin(pugs_within_nonpugs_list)].explore()

In [79]:
clean_public_green_space = public_green_space.overlay(non_public_green_space, how='difference')

In [80]:
clean_public_green_space.explore()

---

# Save classified green spaces

In [81]:
clean_public_green_space.to_file('../data/processed/osm/public_green_spaces_dresden.geojson', driver='GeoJSON')

---

# Create binary mask

In [82]:
# Open the GeoTIFF file
file_path = '../data/raw/sentinel-2/sentinel2_openeo_med_4months_dresden.geotiff'
with rasterio.open(file_path) as dataset:
    # Get the width and height of the image
    width = dataset.width
    height = dataset.height

    # Print the width and height
    print(f"Width: {width} pixels")
    print(f"Height: {height} pixels")

Width: 2747 pixels
Height: 2301 pixels

In [83]:
utils.create_binary_mask(clean_public_green_space, 
                   '../data/processed/osm/public_green_spaces_dresden.geotiff', 
                   '../data/raw/sentinel-2/sentinel2_openeo_med_4months_dresden.geotiff')

Rasterization complete.

---

# Create Signed-distance transform

In [84]:
utils.create_sdt_raster(clean_public_green_space, 
                  '../data/processed/osm/sdt_public_green_spaces_dresden.geotiff',
                  '../data/raw/sentinel-2/sentinel2_openeo_med_4months_dresden.geotiff')

Signed distance transform complete.